### PR TITLE
#11 Added an extension to store response content

### PR DESCRIPTION
**Pull request by fabmoll**
Added an extension to store response content when EnsureSuccessStatusCode throw an exception.

Can you review my code and merge if it's ok for you ? :)

### CODE REVIEW

**Comment by fabmoll** [comment]
You can find the original code that I found on stackoverflow 
http://stackoverflow.com/a/27986405/1565574

**Comment by igorkulman** [comment]
I do not like this solution. It is throwing an exception that does not inherit from `DataServiceException` like the exceptions thrown by the service. 

A better solution would be adding a field to the response to the `ConnectionException` (there already is a filed for the `StatusCode`) and throwing it when not success.

**Comment by fabmoll** [comment]
Ok I'll change it

Envoyé à partir de mon Windows Phone
________________________________
De : Igor Kulman<mailto:notifications@github.com>
Envoyé : ‎03-‎01-‎16 13:37
À : igorkulman/Kulman.WPA81.BaseRestService<mailto:Kulman.WPA81.BaseRestService@noreply.github.com>
Cc : Fabrice Moll<mailto:fabrice.moll@hotmail.com>
Objet : Re: [Kulman.WPA81.BaseRestService] #11 Added an extension to store response content (#12)

I do not like this solution. It is throwing an exception that does not inherit from `DataServiceException` like the exceptions thrown by the service.

A better solution would be adding a field to the response to the `ConnectionException` (there already is a filed for the `StatusCode`) and throwing it when not success.

---

**Comment by igorkulman** [comment]
But if you think your solution is better, just tell me your arguments, maybe you can persuade me :)

**Comment by fabmoll** [comment]
After checking the ConnectionException class I saw that we need to provide the InnerException.

So should I avoid the new EnsureSuccessStatusCodeAsync and keep the previous EnsureSuccessStatusCode?  Then I could catch the HttpRequestException to add the InnerException and set the StatusCode and the string Content.

Like that I remove the HttpResponseMessageExtensions class and the SimpleHttpResponseException class.

**Comment by fabmoll** [comment]
Ok I changed the code.
Decided to remove the Extension class too.

**Pull request merged**
